// Build the Walkthrough Punch List as a real PDF (jsPDF, loaded on demand like
// the JV agreement): Goldstone header, items grouped by room, each with its
// video frame and the snippet it came from ("video 0:38–0:52 · 14 sec").
const fmtT = (t) => `${Math.floor(t / 60)}:${String(Math.floor(Math.max(0, t) % 60)).padStart(2, "0")}`;
export const snippetLabel = (it, multi) => {
  const dur = Math.max(0, Math.round((it.end || 0) - (it.start || 0)));
  const pre = multi ? `video ${it.clip || 1} · ` : "video ";
  return dur > 0 ? `${pre}${fmtT(it.start)}–${fmtT(it.end)} · ${dur} sec` : `${pre}${fmtT(it.start || 0)}`;
};

export async function walkPdfFile({ address, cityLine, dateLabel, contractor, items }) {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ unit: "pt", format: "letter" }); // 612 x 792
  const W = 612, H = 792, margin = 54, maxW = W - margin * 2;
  let y = margin;
  let page = 1;

  const footer = () => {
    doc.setFont("helvetica", "normal"); doc.setFontSize(8); doc.setTextColor(160);
    doc.text(`Page ${page} · Punch List — ${address} · Generated by Goldstone Properties`, W / 2, H - 26, { align: "center" });
    doc.setTextColor(0);
  };
  const ensure = (need) => {
    if (y + need > H - margin - 10) { footer(); doc.addPage(); page += 1; y = margin; }
  };

  // Header
  doc.setFont("times", "bold"); doc.setFontSize(11); doc.setTextColor(184, 145, 46);
  doc.text("GOLDSTONE PROPERTIES", margin, y);
  doc.setTextColor(0);
  if (contractor) {
    doc.setFont("helvetica", "normal"); doc.setFontSize(8); doc.setTextColor(120);
    doc.text("Prepared for:", W - margin, y - 2, { align: "right" });
    doc.setFont("helvetica", "bold"); doc.setFontSize(9.5); doc.setTextColor(40);
    doc.text(String(contractor), W - margin, y + 9, { align: "right" });
    doc.setTextColor(0);
  }
  y += 18;
  doc.setFont("helvetica", "bold"); doc.setFontSize(16);
  doc.text(`Punch List — ${address}`, margin, y);
  y += 15;
  doc.setFont("helvetica", "normal"); doc.setFontSize(9); doc.setTextColor(110);
  doc.text(`${cityLine ? cityLine + " · " : ""}Walkthrough ${dateLabel} · ${items.length} item${items.length !== 1 ? "s" : ""}`, margin, y);
  doc.setTextColor(0);
  y += 8;
  doc.setDrawColor(184, 145, 46); doc.setLineWidth(2);
  doc.line(margin, y, W - margin, y);
  y += 16;

  // Room groups in first-appearance order
  const rooms = [];
  items.forEach((it) => { const r = it.room || "General"; if (!rooms.includes(r)) rooms.push(r); });
  const multiClip = items.some((it) => (it.clip || 1) > 1); // several videos → cite which one

  // Images keep their real shape — phone walkthroughs are portrait, and
  // forcing them into a landscape box stretches them. Fixed column width,
  // aspect-true size capped in height, centered in the column.
  const IMG_W = 118, IMG_MAXH = 150, GAP = 12;
  let n = 0;
  for (const room of rooms) {
    const list = items.filter((it) => (it.room || "General") === room);
    ensure(20 + 90);
    doc.setFont("helvetica", "bold"); doc.setFontSize(9); doc.setTextColor(140);
    doc.text(String(room).toUpperCase(), margin, y);
    doc.setTextColor(0);
    y += 10;
    for (const it of list) {
      n += 1;
      let iw = 0, ih = 0;
      if (it.image) {
        iw = IMG_W; ih = 82;
        try {
          const p = doc.getImageProperties(it.image);
          const r = p.height / p.width;
          if (r > 0 && isFinite(r)) { iw = IMG_W; ih = IMG_W * r; if (ih > IMG_MAXH) { ih = IMG_MAXH; iw = IMG_MAXH / r; } }
        } catch { /* keep default box */ }
      }
      const textX = margin + (it.image ? IMG_W + GAP : 0);
      const textW = maxW - (it.image ? IMG_W + GAP : 0);
      doc.setFont("helvetica", "bold"); doc.setFontSize(10.5);
      const titleLines = doc.splitTextToSize(`${n}. ${it.title}`, textW);
      doc.setFont("helvetica", "normal"); doc.setFontSize(9);
      const detailLines = it.detail ? doc.splitTextToSize(it.detail, textW) : [];
      const textH = titleLines.length * 12 + detailLines.length * 11 + 14;
      const rowH = Math.max(it.image ? ih : 0, textH) + 10;
      ensure(rowH + 6);
      const top = y;
      if (it.image) {
        try { doc.addImage(it.image, "JPEG", margin + (IMG_W - iw) / 2, top, iw, ih); } catch { /* frame missing — text-only row */ }
      }
      let ty = top + 11;
      doc.setFont("helvetica", "bold"); doc.setFontSize(10.5);
      doc.text(titleLines, textX, ty); ty += titleLines.length * 12;
      if (detailLines.length) {
        doc.setFont("helvetica", "normal"); doc.setFontSize(9); doc.setTextColor(70);
        doc.text(detailLines, textX, ty); ty += detailLines.length * 11;
        doc.setTextColor(0);
      }
      doc.setFont("helvetica", "normal"); doc.setFontSize(8); doc.setTextColor(150);
      doc.text(snippetLabel(it, multiClip), textX, ty + 3);
      doc.setTextColor(0);
      y = top + rowH;
      doc.setDrawColor(232); doc.setLineWidth(0.6);
      doc.line(margin, y - 4, W - margin, y - 4);
    }
    y += 8;
  }
  footer();

  const safe = String(address || "property").replace(/[^a-zA-Z0-9 ,.-]/g, "").slice(0, 60);
  return new File([doc.output("blob")], `Punch List - ${safe}.pdf`, { type: "application/pdf" });
}
